apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_ENV: {{ .Values.env.appEnv | quote }}
  DB_HOST: {{ .Values.env.db.host | quote }}
  DB_PORT: {{ .Values.env.db.port | quote }}
  DB_NAME: {{ .Values.env.db.name | quote }}
  DB_SCHEMA: {{ .Values.env.db.schema | quote }}
  REDIS_HOST: {{ .Values.env.redis.host | quote }}
  REDIS_PORT: {{ .Values.env.redis.port | quote }}