apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  SUPERADMIN_USERNAME: {{ .Values.secrets.superadminUsername | quote }}
  SUPERADMIN_PASSWORD: {{ .Values.secrets.superadminPassword | quote }}
  COOKIE_SECRET: {{ .Values.secrets.cookieSecret | quote }}
